---
- name: Configure nginx in REC env 
  hosts: REC
  tasks:
  - name: Install nginx
    apt: 
      name: nginx
      state: latest
  - name: start nginx server
    service:
      name: nginx
      state: started

